package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ban generated by hbm2java
 */
public class BanDTO  implements java.io.Serializable {


     private Integer banId;
     private DiadiemDTO diadiem;
     private Short number;
     private String description;
     private Set hoadons = new HashSet(0);

    public BanDTO() {
    }

    public BanDTO(DiadiemDTO diadiem, Short number, String description, Set hoadons) {
       this.diadiem = diadiem;
       this.number = number;
       this.description = description;
       this.hoadons = hoadons;
    }
   
    public Integer getBanId() {
        return this.banId;
    }
    
    public void setBanId(Integer banId) {
        this.banId = banId;
    }
    public DiadiemDTO getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(DiadiemDTO diadiem) {
        this.diadiem = diadiem;
    }
    public Short getNumber() {
        return this.number;
    }
    
    public void setNumber(Short number) {
        this.number = number;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }




}


