package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bep generated by hbm2java
 */
public class BepDTO  implements java.io.Serializable {


     private Integer bepId;
     private String name;
     private DiadiemDTO diadiem;
     private Set bepHistories = new HashSet(0);

    public BepDTO() {
    }

    public BepDTO(DiadiemDTO diadiem, String name, Set bepHistories) {
       this.diadiem = diadiem;
       this.name = name;
       this.bepHistories = bepHistories;
    }
   
    public Integer getBepId() {
        return this.bepId;
    }
    
    public void setBepId(Integer bepId) {
        this.bepId = bepId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public DiadiemDTO getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(DiadiemDTO diadiem) {
        this.diadiem = diadiem;
    }
    public Set getBepHistories() {
        return this.bepHistories;
    }
    
    public void setBepHistories(Set bepHistories) {
        this.bepHistories = bepHistories;
    }




}


