package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BepHistory generated by hbm2java
 */
public class BepHistoryDTO  implements java.io.Serializable {


     private Integer bepHistoryId;
     private BepDTO bep;
     private String monAnName;
     private Short monAnQuantity;
     private Date monAnOrderTime;
     private Date monAnCompleteTime;

    public BepHistoryDTO() {
    }

    public BepHistoryDTO(BepDTO bep, String monAnName, Short monAnQuantity, Date monAnOrderTime, Date monAnCompleteTime) {
       this.bep = bep;
       this.monAnName = monAnName;
       this.monAnQuantity = monAnQuantity;
       this.monAnOrderTime = monAnOrderTime;
       this.monAnCompleteTime = monAnCompleteTime;
    }
   
    public Integer getBepHistoryId() {
        return this.bepHistoryId;
    }
    
    public void setBepHistoryId(Integer bepHistoryId) {
        this.bepHistoryId = bepHistoryId;
    }
    public BepDTO getBep() {
        return this.bep;
    }
    
    public void setBep(BepDTO bep) {
        this.bep = bep;
    }
    public String getMonAnName() {
        return this.monAnName;
    }
    
    public void setMonAnName(String monAnName) {
        this.monAnName = monAnName;
    }
    public Short getMonAnQuantity() {
        return this.monAnQuantity;
    }
    
    public void setMonAnQuantity(Short monAnQuantity) {
        this.monAnQuantity = monAnQuantity;
    }
    public Date getMonAnOrderTime() {
        return this.monAnOrderTime;
    }
    
    public void setMonAnOrderTime(Date monAnOrderTime) {
        this.monAnOrderTime = monAnOrderTime;
    }
    public Date getMonAnCompleteTime() {
        return this.monAnCompleteTime;
    }
    
    public void setMonAnCompleteTime(Date monAnCompleteTime) {
        this.monAnCompleteTime = monAnCompleteTime;
    }




}


