package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diadiem generated by hbm2java
 */
public class DiadiemDTO  implements java.io.Serializable {


     private Integer diadiemId;
     private String owner_email;
     private String owner_password;
     private String name;
     private String address;
     private String phone;
     private String description;
//     private Set menus = new HashSet(0);
//     private Set hoadons = new HashSet(0);
//     private Set thanhviens = new HashSet(0);
//     private Set beps = new HashSet(0);
//     private Set bans = new HashSet(0);

    public DiadiemDTO() {
    }

    public DiadiemDTO(String ownerEmail, String ownerPassword, String name, String address, String phone, String description, Set menus, Set hoadons, Set thanhviens, Set beps, Set bans) {
       this.owner_email = ownerEmail;
       this.owner_password = ownerPassword;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.description = description;
//       this.menus = menus;
//       this.hoadons = hoadons;
//       this.thanhviens = thanhviens;
//       this.beps = beps;
//       this.bans = bans;
    }
   
    public Integer getDiadiemId() {
        return this.diadiemId;
    }
    
    public void setDiadiemId(Integer diadiemId) {
        this.diadiemId = diadiemId;
    }
    public String getOwner_email() {
        return owner_email;
    }

    public void setOwner_email(String owner_email) {
        this.owner_email = owner_email;
    }
    public String getOwner_password() {
        return owner_password;
    }

    public void setOwner_password(String owner_password) {
        this.owner_password = owner_password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
//    public Set getMenus() {
//        return this.menus;
//    }
//    
//    public void setMenus(Set menus) {
//        this.menus = menus;
//    }
//    public Set getHoadons() {
//        return this.hoadons;
//    }
//    
//    public void setHoadons(Set hoadons) {
//        this.hoadons = hoadons;
//    }
//    public Set getThanhviens() {
//        return this.thanhviens;
//    }
//    
//    public void setThanhviens(Set thanhviens) {
//        this.thanhviens = thanhviens;
//    }
//    public Set getBeps() {
//        return this.beps;
//    }
//    
//    public void setBeps(Set beps) {
//        this.beps = beps;
//    }
//    public Set getBans() {
//        return this.bans;
//    }
//    
//    public void setBans(Set bans) {
//        this.bans = bans;
//    }




}


