package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1



/**
 * HoadonChitiet generated by hbm2java
 */
public class HoadonchitietDTO  implements java.io.Serializable {


     private Integer hoadonChitietId;
     private HoadonDTO hoadon;
     private String monAnName;
     private Short monAnQuantity;
     private Integer monAnUnitPrice;
     private Integer monAnTotalPrice;

    public HoadonchitietDTO() {
    }

    public HoadonchitietDTO(HoadonDTO hoadon, String monAnName, Short monAnQuantity, Integer monAnUnitPrice, Integer monAnTotalPrice) {
       this.hoadon = hoadon;
       this.monAnName = monAnName;
       this.monAnQuantity = monAnQuantity;
       this.monAnUnitPrice = monAnUnitPrice;
       this.monAnTotalPrice = monAnTotalPrice;
    }
   
    public Integer getHoadonchitietId() {
        return this.hoadonChitietId;
    }
    
    public void setHoadonchitietId(Integer hoadonChitietId) {
        this.hoadonChitietId = hoadonChitietId;
    }
    public HoadonDTO getHoadon() {
        return this.hoadon;
    }
    
    public void setHoadon(HoadonDTO hoadon) {
        this.hoadon = hoadon;
    }
    public String getMonAnName() {
        return this.monAnName;
    }
    
    public void setMonAnName(String monAnName) {
        this.monAnName = monAnName;
    }
    public Short getMonAnQuantity() {
        return this.monAnQuantity;
    }
    
    public void setMonAnQuantity(Short monAnQuantity) {
        this.monAnQuantity = monAnQuantity;
    }
    public Integer getMonAnUnitPrice() {
        return this.monAnUnitPrice;
    }
    
    public void setMonAnUnitPrice(Integer monAnUnitPrice) {
        this.monAnUnitPrice = monAnUnitPrice;
    }
    public Integer getMonAnTotalPrice() {
        return this.monAnTotalPrice;
    }
    
    public void setMonAnTotalPrice(Integer monAnTotalPrice) {
        this.monAnTotalPrice = monAnTotalPrice;
    }




}


