package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1


import DTO.DiadiemDTO;
import DTO.BanDTO;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoadon generated by hbm2java
 */
public class HoadonDTO  implements java.io.Serializable {


     private Integer hoadonId;
     private BanDTO ban;
     private DiadiemDTO diadiem;
     private Date date;
     private Integer totalPrice;
     private Integer money;
     private Integer charge;
     private Set hoadonChitiets = new HashSet(0);

    public HoadonDTO() {
    }

    public HoadonDTO(BanDTO ban, DiadiemDTO diadiem, Date date, Integer totalPrice, Integer money, Integer charge, Set hoadonChitiets) {
       this.ban = ban;
       this.diadiem = diadiem;
       this.date = date;
       this.totalPrice = totalPrice;
       this.money = money;
       this.charge = charge;
       this.hoadonChitiets = hoadonChitiets;
    }
   
    public Integer getHoadonId() {
        return this.hoadonId;
    }
    
    public void setHoadonId(Integer hoadonId) {
        this.hoadonId = hoadonId;
    }
    public BanDTO getBan() {
        return this.ban;
    }
    
    public void setBan(BanDTO ban) {
        this.ban = ban;
    }
    public DiadiemDTO getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(DiadiemDTO diadiem) {
        this.diadiem = diadiem;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Integer getMoney() {
        return this.money;
    }
    
    public void setMoney(Integer money) {
        this.money = money;
    }
    public Integer getCharge() {
        return this.charge;
    }
    
    public void setCharge(Integer charge) {
        this.charge = charge;
    }
    public Set getHoadonChitiets() {
        return this.hoadonChitiets;
    }
    
    public void setHoadonChitiets(Set hoadonChitiets) {
        this.hoadonChitiets = hoadonChitiets;
    }




}


