package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1



/**
 * MenuChitiet generated by hbm2java
 */
public class MenuchitietDTO  implements java.io.Serializable {


     private Integer menuChitietId;
     private MenuDTO menu;
     private String name;
     private Integer price;
     private String picture;
     private Boolean status;

    public MenuchitietDTO() {
    }

    public MenuchitietDTO(MenuDTO menu, String name, Integer price, String picture, Boolean status) {
       this.menu = menu;
       this.name = name;
       this.price = price;
       this.picture = picture;
       this.status = status;
    }
   
    public Integer getMenuchitietId() {
        return this.menuChitietId;
    }
    
    public void setMenuchitietId(Integer menuChitietId) {
        this.menuChitietId = menuChitietId;
    }
    public MenuDTO getMenu() {
        return this.menu;
    }
    
    public void setMenu(MenuDTO menu) {
        this.menu = menu;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


