package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1


import DTO.DiadiemDTO;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class MenuDTO  implements java.io.Serializable {


     private Integer menuId;
     private DiadiemDTO diadiem;
     private String name;
     private Set menuChitiets = new HashSet(0);

    public MenuDTO() {
    }

    public MenuDTO(DiadiemDTO diadiem, String name, Set menuChitiets) {
       this.diadiem = diadiem;
       this.name = name;
       this.menuChitiets = menuChitiets;
    }
   
    public Integer getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
    public DiadiemDTO getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(DiadiemDTO diadiem) {
        this.diadiem = diadiem;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getMenuChitiets() {
        return this.menuChitiets;
    }
    
    public void setMenuChitiets(Set menuChitiets) {
        this.menuChitiets = menuChitiets;
    }




}


