package DTO;
// Generated Jan 13, 2016 10:56:57 AM by Hibernate Tools 4.3.1

import DTO.DiadiemDTO;




/**
 * Thanhvien generated by hbm2java
 */
public class ThanhvienDTO  implements java.io.Serializable {


     private Integer thanhvienId;
     private DiadiemDTO diadiem;
     private String name;
     private String cmnd;
     private String contry;
     private String address;
     private String phone;
     private String username;
     private String password;
     private String email;
     private Boolean isApproved;

    public ThanhvienDTO() {
    }

    public ThanhvienDTO(DiadiemDTO diadiem, String name, String cmnd, String contry, String address, String phone, String username, String password, String email, Boolean isApproved) {
       this.diadiem = diadiem;
       this.name = name;
       this.cmnd = cmnd;
       this.contry = contry;
       this.address = address;
       this.phone = phone;
       this.username = username;
       this.password = password;
       this.email = email;
       this.isApproved = isApproved;
    }
   
    public Integer getThanhvienId() {
        return this.thanhvienId;
    }
    
    public void setThanhvienId(Integer thanhvienId) {
        this.thanhvienId = thanhvienId;
    }
    public DiadiemDTO getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(DiadiemDTO diadiem) {
        this.diadiem = diadiem;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getContry() {
        return this.contry;
    }
    
    public void setContry(String contry) {
        this.contry = contry;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getIsApproved() {
        return this.isApproved;
    }
    
    public void setIsApproved(Boolean isApproved) {
        this.isApproved = isApproved;
    }




}


